# Generated by Django 3.2.8 on 2022-01-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='folder',
            field=models.ManyToManyField(null=True, related_name='all_bm_folder', to='backend.Folder'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='tag',
            field=models.ManyToManyField(null=True, related_name='all_bm_tag', to='backend.Tag'),
        ),
    ]
