# Generated by Django 3.2.8 on 2022-01-16 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220105_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='folder',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_bm_folder', to='backend.folder'),
        ),
    ]
